;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-M-x
	kill-region
	repeat
	sp-backward-delete-char
	sp-backward-kill-word
	sp-backward-unwrap-sexp
	sp-forward-sexp
	sp-kill-hybrid-sexp
	sp-kill-word
	sp-split-sexp
	))

(setq mc/cmds-to-run-once
      '(
	keyboard-escape-quit
	sp-delete-char
	))
